### ISSUE TITLE
When pausing a device fails the device can get in an invalid state (even after reboot)

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#184]
When a device is paused, but there is a problem in the backend (e.g. an OOM), the device can get in the following state:

* enabled: false
* paused: true

Usually, this is the normal pausing state, but there is no DeviceReactivator in the PauseDeviceController, so if the backend is asked for the remaining seconds to pause the device, it gets 0.

This leads to strange UI behaviour: in the Settings / Devices details the device seems to be enabled (because the switch is wired to `vm.pausedOrEnabled`). The pause switch is off but flickers every 4 seconds.

When eBlocker is restarted this should be cleaned up by the StartupTask. But it fails due to a race condition:

    2021-10-25 17:00:46,061 [ERROR]                   org.eblocker.server.common.executor.LoggingExecutorService [pool-3-thread-1] - executor lowPrioScheduledExecutor-22: exception in StartupTask
    java.lang.IllegalStateException: method call not allowed on uninitialized service
        at org.eblocker.server.common.ssl.SslService.requireInitialization(SslService.java:374)
        at org.eblocker.server.common.ssl.SslService.isSslEnabled(SslService.java:142)
        at org.eblocker.server.common.startup.SubSystemUsageInterceptor.invoke(SubSystemUsageInterceptor.java:59)
        at org.eblocker.server.http.service.DeviceService.updateIconStatus(DeviceService.java:137)
        at org.eblocker.server.http.service.DeviceService.updateDevice(DeviceService.java:120)
        at org.eblocker.server.common.startup.SubSystemUsageInterceptor.invoke(SubSystemUsageInterceptor.java:59)
        at org.eblocker.server.common.PauseDeviceController.reactivateDevice(PauseDeviceController.java:113)
        at org.eblocker.server.common.util.StartupTask.run(StartupTask.java:39)
        at org.eblocker.server.common.executor.LoggingExecutorService$CallableRunnable.call(LoggingExecutorService.java:267)
        at org.eblocker.server.common.executor.LoggingExecutorService$LoggingCallable.call(LoggingExecutorService.java:213)
        at org.eblocker.server.common.executor.LoggingExecutorService$RunnableCallable.run(LoggingExecutorService.java:249)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

There seems to be a race between the BackgroundServices which schedules the StartupTask after 10 seconds and the initialization of the SSL subsystem by the EblockerServerApp.

**Comment by eblosug** [comment]
Currently the only workaround is resetting the device in Settings / Devices / Device details.

**Comment by eblosug** [comment]
One reason for the invalid state that I have observed when pausing a device:

    2021-10-23 09:41:32,454 [ERROR] aaa935aa 0cc6b4b2 org.eblocker.server.common.system.LoggingProcess [pool-1-thread-304] -
        dhcpd-apply-config: Could not apply DHCP server configuration:
        Config file '/opt/eblocker-icap/network/dhcpd.conf' does not exist.
    2021-10-23 09:41:32,508 [ERROR] aaa935aa 238ddb2d org.eblocker.server.http.server.ExceptionLogger [defaultEventExecutorGroup-4-3] -
        Returning 500 Internal Server Error for PUT https://192.168.1.2:3000/api/device/pause/device:8c861e0da5ca 
        caused by org.eblocker.server.common.exceptions.EblockerException:
            Could not apply DHCP server configuration. Return value: 1
