### ISSUE TITLE
Resetting eBlocker's activation sometimes fails

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#240]
When eBlocker's activation is resetted, sometimes an NPE is thrown:

    Returning 500 Internal Server Error for DELETE https://192.168.0.103:3000/api/adminconsole/registration caused by java.lang.NullPointerException: null
    java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:?]
        at java.util.Properties.put(Properties.java:1340) ~[?:?]
        at java.util.Properties.setProperty(Properties.java:228) ~[?:?]
        at org.eblocker.server.common.registration.DeviceRegistrationProperties.store(DeviceRegistrationProperties.java:272) ~[eblocker-icapserver_2.9-SNAPSHOT.20220322144430_all.jar:2.9-SNAPSHOT]
        at org.eblocker.server.common.registration.DeviceRegistrationProperties.reset(DeviceRegistrationProperties.java:205) ~[eblocker-icapserver_2.9-SNAPSHOT.20220322144430_all.jar:2.9-SNAPSHOT]
        at org.eblocker.server.http.controller.impl.DeviceRegistrationControllerImpl.resetRegistration(DeviceRegistrationControllerImpl.java:269) ~[eblocker-icapserver_2.9-SNAPSHOT.20220322144430_all.jar:2.9-SNAPSHOT]
    ...

**Comment by eblosug** [comment]
The issue occurs often when the macOS or iOS app is open. It can also be reproduced by starting the activation reset via the UI and immediately sending a few requests to `/registration` with curl.

The NPE is caused by a race condition:

* `DeviceRegistrationProperties.reset()` sets `registrationState` to `NEW`
* New certificates are created which takes a few seconds
* In the meantime requests to `/registration` call `DeviceRegistrationProperties.getRegistrationState()` which resets `registrationState` to `OK`
* The method `store()` is called by `reset()` which crashes, because `hasBeenRegisteredBefore()` returns `true` but many attributes (e.g. `deviceName`) are `null`.

**Comment by eblosug** [comment]
Fixed by #241
