### ISSUE TITLE
ICAP error on large HTML pages (> 8 MB)

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#342]
When a large HTML page (> 8 MB) is requested eBlocker responds with an ICAP error message.

Some pages contain many inline images, for example <https://transformer-circuits.pub/2024/scaling-monosemanticity/index.html>.

The error log shows a `TooLongFrameException`:

    2024-05-27T16:53:52,791 [WARN ] 5d26ead6 ce670d7f org.eblocker.server.icap.ch.mimo.icap.IcapRequestHandler [pool-2-thread-20] - Unexpected error in ICAP request handler: 
    io.netty.handler.codec.TooLongFrameException: ICAP content length exceeded [8388608] bytes
        at ch.mimo.netty.handler.codec.icap.IcapChunkAggregator.channelRead(IcapChunkAggregator.java:152) ~[netty-icap-2.1.5.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) [netty-codec-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:349) [netty-codec-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) [netty-codec-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.84.Final.jar:4.1.84.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.84.Final.jar:4.1.84.Final]
        at org.eblocker.server.common.executor.LoggingExecutorService$CallableRunnable.call(LoggingExecutorService.java:269) [eblocker-icapserver_3.1.0.20240322084809_all.jar:3.1.0]
        at org.eblocker.server.common.executor.LoggingExecutorService$LoggingCallable.call(LoggingExecutorService.java:213) [eblocker-icapserver_3.1.0.20240322084809_all.jar:3.1.0]
        at org.eblocker.server.common.executor.LoggingExecutorService$RunnableCallable.run(LoggingExecutorService.java:250) [eblocker-icapserver_3.1.0.20240322084809_all.jar:3.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by eblosug** [comment]
A better behaviour would be:

* Do not try to load large pages via ICAP
* Let the squid process the response unmodified
* So the page would load in the browser but without the Controlbar icon.
