### ISSUE TITLE
Debian Bookworm: permission denied opening file in /tmp

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#347]
On Debian Bookworm the Icapserver logs this every 20 seconds:

    2024-06-27T08:30:04,118 [ERROR]                   org.eblocker.server.common.system.LoggingProcess [pool-2-thread-37] -
        dump_iptables_rules:
        /opt/eblocker-icap/scripts/dump_iptables_rules: line 18:
        /tmp/iptables-rules12752035995256054746.tmp: Permission denied
    2024-06-27T08:30:04,119 [ERROR]                   org.eblocker.server.common.network.TrafficAccounter [pool-4-thread-2] - failed to update network activity
      org.eblocker.server.common.network.TrafficAccounter$IpTablesException: ip tables rules dump script failed with exit code 1
        at org.eblocker.server.common.network.TrafficAccounter.getIpTableRulesDump(TrafficAccounter.java:124) ~[eblocker-icapserver_3.1.0.20240514155952_all.jar:3.1.0]
        at org.eblocker.server.common.network.TrafficAccounter.update(TrafficAccounter.java:112) ~[eblocker-icapserver_3.1.0.20240514155952_all.jar:3.1.0]
        at org.eblocker.server.common.network.TrafficAccounter$$EnhancerByGuice$$213964335.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:74) ~[guice-5.0.1.jar:?]
        at org.eblocker.server.common.startup.SubSystemUsageInterceptor.invoke(SubSystemUsageInterceptor.java:43) ~[eblocker-icapserver_3.1.0.20240514155952_all.jar:3.1.0]
        at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:75) ~[guice-5.0.1.jar:?]
        at com.google.inject.internal.InterceptorStackCallback.invoke(InterceptorStackCallback.java:55) ~[guice-5.0.1.jar:?]
        at org.eblocker.server.common.network.TrafficAccounter$$EnhancerByGuice$$213964335.update(<generated>) ~[?:?]
        ...

The file belongs to `icapd`:

    -rw------- 1 icapd icapd 0 Jun 19 16:58 /tmp/iptables-rules12752035995256054746.tmp

But `dump_iptables_rules` runs as root. Why can't it write the above file?

**Comment by eblosug** [comment]
See also: <https://superuser.com/a/1692594>

On Debian Bookworm, `systemd` sets this default:

    sysctl fs.protected_regular=2

The user `icapd` creates a file in `/tmp` which is a sticky directory. The script `dump_iptables_rules` (running as root) tries to write to this file using shell redirection which opens the file with `O_CREAT`. This is not allowed with the above default.
