### ISSUE TITLE
Domain blocking service on port 7777 crashes after receiving an invalid message

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#354]
How to reproduce this issue:

* Log in via SSH on the eBlocker
* Send an invalid IP address to port 7777, e.g.: `echo "X192.168.178.42 dns example.com -" | nc -W 1 -u 127.0.0.1 7777`
* There is no response
* Further requests with valid IP addresses will be ignored

Log file:

    2024-08-01T08:59:52,438 [WARN ] d1b42316 -------- org.eblocker.server.common.blacklist.RequestHandler
        [pool-2-thread-19] - exception while processing requests
    java.lang.NumberFormatException: For input string: "X192"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at org.eblocker.server.common.data.Ip4Address.parse(Ip4Address.java:40) ~[eblocker-icapserver_3.1.0.20240322084809_all.jar:3.1.0]
        at org.eblocker.server.common.data.IpAddress.parse(IpAddress.java:48) ~[eblocker-icapserver_3.1.0.20240322084809_all.jar:3.1.0]
        at org.eblocker.server.common.blacklist.RequestHandler.channelRead0(RequestHandler.java:75) ~[eblocker-icapserver_3.1.0.20240322084809_all.jar:3.1.0]
    ...

**Comment by eblosug** [comment]
Will be fixed in version 3.2 (or 4.0)
